### ISSUE TITLE
Eval bug: convert  Meta-Llama-3.1-8B-Instruct to gguf failed

### ISSUE THREAD

**Issue by cqray1990** [ggml-org/llama.cpp#10634]
### Name and Version

ubantu 20.04 verson latest

### Operating systems

Linux

### GGML backends

CUDA

### Hardware

A6000

### Models

Meta-Llama-3.1-8B-Instruct

### Problem description & steps to reproduce

python   convert_hf_to_gguf.py Meta-Llama-3.1-8B-Instruct

### Relevant log output

Traceback (most recent call last):
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 1525, in set_vocab
    self._set_vocab_sentencepiece()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 748, in _set_vocab_sentencepiece
    tokens, scores, toktypes = self._create_vocab_sentencepiece()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 765, in _create_vocab_sentencepiece
    raise FileNotFoundError(f"File not found: {tokenizer_path}")
FileNotFoundError: File not found: /media/user/2.0TB/llmmodel/llam_factory/Meta-Llama-3.1-8B-Instruct/tokenizer.model

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 1528, in set_vocab
    self._set_vocab_llama_hf()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 840, in _set_vocab_llama_hf
    vocab = gguf.LlamaHfVocab(self.dir_model)
  File "chatglm/llm_ki/ollama_api/llama.cpp/gguf-py/gguf/vocab.py", line 384, in __init__
    raise TypeError('Llama 3 must be converted with BpeVocab')
TypeError: Llama 3 must be converted with BpeVocab

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 4430, in main
    model_instance.write()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 435, in write
    self.prepare_metadata(vocab_only=False)
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 428, in prepare_metadata
    self.set_vocab()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 1531, in set_vocab
    self._set_vocab_gpt2()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 684, in _set_vocab_gpt2
    tokens, toktypes, tokpre = self.get_vocab_base()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 512, in get_vocab_base
    tokenizer = AutoTokenizer.from_pretrained(self.dir_model)
  File "anaconda3/envs/langchain_env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 837, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "anaconda3/envs/langchain_env/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 958, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "anaconda3/envs/langchain_env/lib/python3.10/site-packages/transformers/configuration_utils.py", line 768, in from_dict
    config = cls(**config_dict)
  File "anaconda3/envs/langchain_env/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
    self._rope_scaling_validation()
  File "anaconda3/envs/langchain_env/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 182, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}

llama.cpp/convert_hf_to_gguf.py", line 1531, in set_vocab
    self._set_vocab_gpt2()
  File "chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 684, in _set_vocab_gpt2
    tokens, toktypes, tokpre = self.get_vocab_base()
  File "/chatglm/llm_ki/ollama_api/llama.cpp/convert_hf_to_gguf.py", line 514, in get_vocab_base
    assert max(tokenizer.vocab.values()) < vocab_size
AssertionError

**Comment by tetron** [comment]
I am trying to convert the Llama 3.3 70B safetensors from HuggingFace and getting the same error.

**Comment by tetron** [comment]
> I am trying to convert the Llama 3.3 70B safetensors from HuggingFace and getting the same error.

So, for me, it looks like I was running outdated code.

I was using the ROCm container image (`ghcr.io/ggerganov/llama.cpp:full-rocm`).  I did some poking around, and I can't tell when that image was last updated -- it seems that the containers images for CPU, CUDA and MUSA are built regularly, but not any of the others.

**Comment by FlyChary** [comment]
你复制原始的special_tokens_map.json、tokenizer.json、tokenizer_config.json，到你需要转换模型的目录，并覆盖这些文件，就可以正常导出了

Copy the original special_tokens_map.json, tokenizer.json, and tokenizer_config.json files into the directory of the model you want to convert, then overwrite the existing files. This should allow the export to proceed normally.
